export const LANG_DATA: any = {
  en: { nowTime: 'Current Time', adhan: 'Adhan', iqamah: 'Iqamah', itIsTime: 'It is time for prayer', prepare: 'Prepare for prayer', iqIn: 'Iqamah in', nextPrayer: 'Next Prayer', friday: 'Friday Prayer — Iqamah', closingIn: 'Closing in ', noIq: 'No Iqamah', days: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'], months: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'], pn: { Fajr: 'FAJR', Shuruq: 'SHURUQ', Dhuhr: 'DHUHR', Asr: 'ASR', Maghrib: 'MAGHRIB', Isha: 'ISHA' }, quranLbl: 'Quranic Reminder', hadithLbl: 'Hadith of the Day', annLbl: 'Mosque Announcements', cleanTitle: 'Keep the Mosque Clean', cleanSub: 'Cleanliness is half of faith', darsTag: 'Weekly Invitation' },
  it: { nowTime: 'Orario Attuale', adhan: 'Adhan', iqamah: 'Iqamah', itIsTime: "È l'ora della preghiera", prepare: 'Preparatevi per la preghiera', iqIn: 'Iqamah tra', nextPrayer: 'Prossima Preghiera', friday: 'Preghiera del Venerdì — Iqamah', closingIn: 'Chiude tra ', noIq: 'Nessuna Iqamah', days: ['Domenica', 'Lunedì', 'Martedì', 'Mercoledì', 'Giovedì', 'Venerdì', 'Sabato'], months: ['Gennaio', 'Febbraio', 'Marzo', 'Aprile', 'Maggio', 'Giugno', 'Luglio', 'Agosto', 'Settembre', 'Ottobre', 'Novembre', 'Dicembre'], pn: { Fajr: 'FAJR', Shuruq: 'SHURUQ', Dhuhr: 'DHUHR', Asr: 'ASR', Maghrib: 'MAGHRIB', Isha: 'ISHA' }, quranLbl: 'Promemoria Coranico', hadithLbl: 'Hadith del Giorno', annLbl: 'Avvisi della Moschea', cleanTitle: 'Mantieni la Moschea Pulita', cleanSub: 'La pulizia è metà della fede', darsTag: 'Invito Settimanale' },
  ar: { nowTime: 'الوقت الآن', adhan: 'أذان', iqamah: 'إقامة', itIsTime: 'حان وقت الصلاة', prepare: 'استعدوا للصلاة', iqIn: 'الإقامة بعد', nextPrayer: 'الصلاة القادمة', friday: 'صلاة الجمعة — الإقامة', closingIn: 'يغلق خلال ', noIq: 'لا إقامة', days: ['الأحد', 'الاثنين', 'الثلاثاء', 'الأربعاء', 'الخميس', 'الجمعة', 'السبت'], months: ['يناير', 'فبراير', 'مارس', 'أبريل', 'مايو', 'يونيو', 'يوليو', 'أغسطس', 'سبتمبر', 'أكتوبر', 'نوفمبر', 'ديسمبر'], pn: { Fajr: 'الفجر', Shuruq: 'الشروق', Dhuhr: 'الظهر', Asr: 'العصر', Maghrib: 'المغرب', Isha: 'العشاء' }, quranLbl: 'تذكير قرآني', hadithLbl: 'حديث اليوم', annLbl: 'إعلانات المسجد', cleanTitle: 'حافظ على نظافة المسجد', cleanSub: 'النظافة من الإيمان', darsTag: 'دعوة أسبوعية' },
  bn: { nowTime: 'বর্তমান সময়', adhan: 'আযান', iqamah: 'ইকামত', itIsTime: 'নামাযের সময় হয়েছে', prepare: 'নামাযের জন্য প্রস্তুত হন', iqIn: 'ইকামত শুরু হবে', nextPrayer: 'পরবর্তী নামায', friday: 'জুমার নামায — ইকামত', closingIn: 'বন্ধ হবে ', noIq: 'ইকামত নেই', days: ['রবিবার', 'সোমবার', 'মঙ্গলবার', 'বুধবার', 'বৃহস্পতিবার', 'শুক্রবার', 'শনিবার'], months: ['জানুয়ারি', 'ফেব্রুয়ারি', 'মার্চ', 'এপ্রিল', 'মে', 'জুন', 'জুলাই', 'আগস্ট', 'সেপ্টেম্বর', 'অক্টোবর', 'নভেম্বর', 'ডিসেম্বর'], pn: { Fajr: 'ফজর', Shuruq: 'সূর্যোদয়', Dhuhr: 'যোহর', Asr: 'আসর', Maghrib: 'মাগরিব', Isha: 'এশা' }, quranLbl: 'কুরআনিক স্মরণ', hadithLbl: 'আজকের হাদিস', annLbl: 'মসজিদের ঘোষণা', cleanTitle: 'মসজিদ পরিষ্কার রাখুন', cleanSub: 'পবিত্রতা ঈমানের অর্ধেক', darsTag: 'সাপ্তাহিক আমন্ত্রণ' }
};

export function L(lang: string, key: string): string {
  return LANG_DATA[lang]?.[key] ?? LANG_DATA.en[key] ?? key;
}

export function Lpn(lang: string, key: string): string {
  return LANG_DATA[lang]?.pn?.[key] ?? key;
}
